//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.16 at 11:23:28 AM EST 
//

// new namespace = "", xmlns = {@XmlNs(prefix = "ds", namespaceURI = "http://www.w3.org/2000/09/xmldsig#")},  elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED
// old namespace = "http://uri.etsi.org/02231/v2#"  elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED
@javax.xml.bind.annotation.XmlSchema(namespace = "http://uri.etsi.org/02231/v2#",  elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.zeva.temp.jaxb.datamodel;
//import javax.xml.bind.annotation.XmlNs;

// no Sig: namespace = "http://uri.etsi.org/02231/v2#", xmlns = {@XmlNs(prefix = "ds", namespaceURI = "http://www.w3.org/2000/09/xmldsig#")}, elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED // http://uri.etsi.org/02231/v2# // "http://uri.etsi.org/19612/TSLTag"
// http://www.w3.org/XML/1998/namespace