//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.16 at 11:23:28 AM EST 
//


package com.zeva.temp.jaxb.datamodel;

import java.io.ByteArrayInputStream;
import java.security.cert.CertificateException;
import java.security.cert.CertificateFactory;
import java.security.cert.X509Certificate;
import java.util.ArrayList;
import java.util.List;

import javafx.beans.property.SimpleObjectProperty;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import com.zeva.tlGen.dataModel.CertificateBean;
import com.zeva.tlGen.dataModel.ProviderAttribute;


/**
 * <p>Java class for TSPServiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TSPServiceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://uri.etsi.org/02231/v2#}ServiceInformation"/>
 *         &lt;element ref="{http://uri.etsi.org/02231/v2#}ServiceHistory" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TSPServiceType", propOrder = {
    "serviceInformation",
    "serviceHistory"
})
public class TSPServiceType extends ProviderAttribute{

    @XmlElement(name = "ServiceInformation", required = true)
    protected TSPServiceInformationType serviceInformation;
    @XmlElement(name = "ServiceHistory")
    protected ServiceHistoryType serviceHistory;
    
    @XmlTransient
    private SimpleObjectProperty<ProviderAttribute> nameProp;
    
    public TSPServiceType(){  }

    /**
     * Gets the value of the serviceInformation property.
     * 
     * @return
     *     possible object is
     *     {@link TSPServiceInformationType }
     *     
     */
    public TSPServiceInformationType getServiceInformation() {
        return serviceInformation;
    }

    /**
     * Sets the value of the serviceInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSPServiceInformationType }
     *     
     */
    public void setServiceInformation(TSPServiceInformationType value) {
        this.serviceInformation = value;
    }

    /**
     * Gets the value of the serviceHistory property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceHistoryType }
     *     
     */
    public ServiceHistoryType getServiceHistory() {
        return serviceHistory;
    }

    /**
     * Sets the value of the serviceHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceHistoryType }
     *     
     */
    public void setServiceHistory(ServiceHistoryType value) {
        this.serviceHistory = value;
    }
    
	@Override
	public SimpleObjectProperty<ProviderAttribute> nameProperty() {
		// TODO Auto-generated method stub
		return nameProp;
	}

	@Override
	public ProviderAttributeType getType() {
		// TODO Auto-generated method stub
		return ProviderAttributeType.SERVICE;
	}

	/**
	 * Use of this method assumed a check has been placed using the 
	 * getType() first to determine the Type of this subclass
	 */
	@SuppressWarnings("unchecked")
	@Override
	public TSPServiceType getEncapsulatedBean() {
		// TODO Auto-generated method stub
		return this;
	}


	@Override
	public String getStringName() {
		
		return this.getServiceInformation().getServiceName().getName().get(0).getValue();
	}
	
	public String get1stServiceName(){
		return this.getServiceInformation().getServiceName().getName().get(0).getValue();
	}
	
	/**
	 * Compares the Service name for uniqueness
	 * @param object
	 * @return
	 */
	@Override
	public boolean equals(Object object){
		if(object instanceof TSPServiceType){
			TSPServiceType service = (TSPServiceType)object;
			return service.get1stServiceName().equals(this.get1stServiceName());
		}else{
			return false;
		}
	}
	
	public List<X509Certificate> getServiceCerts(){
		List<X509Certificate> temp = new ArrayList<>();
		CertificateFactory fact;
		try {
			fact = CertificateFactory.getInstance("X.509");
			for(DigitalIdentityType cert : serviceInformation.getServiceDigitalIdentity().getDigitalId()){
				if(cert.getX509Certificate() != null){
					temp.add((X509Certificate)fact.generateCertificate(new ByteArrayInputStream(cert.getX509Certificate())));
				}
			}
		} catch (CertificateException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
		return temp;
	}
	
	public List<ProviderAttribute> getCerts(){
		List<ProviderAttribute> temp = new ArrayList<>();
		for(DigitalIdentityType cert : serviceInformation.getServiceDigitalIdentity().getDigitalId()){
			if(cert.getX509Certificate() != null){
				temp.add(cert.initialize());
			}
		}
				
		return temp;
	}
	
	public List<DigitalIdentityType> getAllDigitalIDs(){
		return this.getServiceInformation().getServiceDigitalIdentity().getDigitalId();
	}
	
	public String toString(){
		TSPServiceInformationType info = serviceInformation;
		StringBuilder builder = new StringBuilder();
		builder.append("Name: " + info.getServiceName() + "\n");
		builder.append("Type: " + info.getServiceTypeIdentifier() + "\n");
		builder.append("Status: " + info.getServiceStatus() + "\n");
		builder.append("Certificates:\n");
		
		for(X509Certificate cert : getServiceCerts()){
			CertificateBean bean = new CertificateBean(cert);
			builder.append("\t" + bean.getStringName() + "\n");
		}
		
		builder.append("Service Def." + info.getTSPServiceDefinitionURI() + "\n");
		builder.append("Start Time: " + info.getStatusStartingTime() + "\n");
		
		return builder.toString();
	}

	@Override
	public ProviderAttribute initialize() {
		this.nameProp = new SimpleObjectProperty<>(this);
		return this;
	}

}
